### ISSUE TITLE
Custom list restore bug

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#57]
When an archive has been restored, the custom listview clears itself and shows just the game the archive was restored for and no other games until the list is manually refreshed.

NOTE: Also noticed that the custom listview isn't scrollable.

**Comment by sanmadjack** [comment]
That's...interesting...can't believe I didn't catch that it hasn't been scrolling.

**Comment by sanmadjack** [comment]
http://goo.gl/GQOuW Give this a try, should be fixed.

**Comment by AdmiringWorm** [comment]
I See scrolling works, but the original issue was not fixed. The scrolling was just a note because I didn't want to create an issue just for that.

**Comment by sanmadjack** [comment]
Ha! Forgot the main point, didn't I :)

**Comment by AdmiringWorm** [comment]
hehe, seems so. 

If you are unsure of what I'm talking about I can post a couple of screen shots of what I mean...

**Comment by AdmiringWorm** [comment]
Below is two screenshots of what I mean.
1st one is before restoring a single archive,
the second one is after (this time it showed three games)
![Before Restoring](http://i47.tinypic.com/283vbn.jpg)
![After Restoring](http://i47.tinypic.com/1eqbzn.jpg)

**Comment by sanmadjack** [comment]
Craziness!

**Comment by sanmadjack** [comment]
I found out what was causing this, and I'm certain that I fixed this bug before. The fix must have gotten lost somewhere, but at least I know exactly how to fix it.

**Comment by sanmadjack** [comment]
Alright here's a build with a fix:
http://goo.gl/GQOuW

**Comment by AdmiringWorm** [comment]
seems like it is fixed now.
I'll test it out some more to see if there is any undesired effects.
But I'll close the issue for now...
